#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoA,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//#include "HTIRS2-driver.h"

void encoderReset()
{
	nMotorEncoder[motorLeft] = 0;
	nMotorEncoder[motorRight] = 0;
}

void moveForward()
{
	motor[motorLeft] = 100;
	motor[motorRight] = 100;
}

void moveBackward()
{
	motor[motorLeft] = -100;
	motor[motorRight] = -100;
}

void stop()
{
	motor[motorLeft] = 0;
	motor[motorRight] = 0;
}

void goRotations(float rotations)
{
	encoderReset();

	while((nMotorEncoder[motorLeft] < 1440 * rotations) && (nMotorEncoder[motorRight] < 1440 * rotations)) {
		moveForward();
	}

	stop();

	encoderReset();
}

void turnRight(float rotations)
{
	encoderReset();

	while((nMotorEncoder[motorRight] < 1440 * rotations) && (nMotorEncoder[motorLeft] < 1440 * rotations))
	{
		motor[motorLeft] = 100;
		motor[motorRight] = -100;
	}

	stop();

	encoderReset();
}

void turnLeft(float rotations)
{
	encoderReset();

	while((nMotorEncoder[motorLeft] < 1440 * rotations) && (nMotorEncoder[motorRight] < 1440 * rotations))
	{
		motor[motorLeft] = -100;
		motor[motorRight] = 100;
	}

	stop();

	encoderReset();
}

task main()
{
	int my_num = 123;
	int path = 1;
	int direction = 0;

	//tHTIRS2DSPMode _mode = DSP_1200;
	//direction = HTIRS2readACDir(HTIRS2);

	//waitForStart(); //DONT FORGET TO ENABLE THIS AGAIN!!!!!!!!!!!!

	encoderReset();

	eraseDisplay();
	nxtDisplayCenteredTextLine(3, "Test=%d", my_num);
	PlaySound(soundBeepBeep);
	//Go to middle of ring

	goRotations(4);
	turnLeft(1.75);
	wait1Msec(500);

	//Add code to figure out what path to take here


	//Start the choice

	if(path == 1) {
		goRotations(3);
		turnLeft(10);
		goRotations(4);
		turnLeft(9);
	}
	else if(path == 2) {
		turnLeft(8.5);
		goRotations(8.2);
	}
	else if(path == 3) {

	}
	else {

	}


}
